### ISSUE TITLE
Prefer includes instead of contains

### ISSUE THREAD

**Issue by ykaragol** [bmeurant/ember-array-contains-helper#15]
While using with Ember's latest versions, a deprecation warning has been raised.

http://emberjs.com/blog/2016/07/25/ember-2-7-and-2-8-beta-released.html#toc_code-enumerable-includes-code-and-code-array-includes-code

**Comment by bmeurant** [comment]
Thank you for reporting. 

I will be able to work on it on sunday, I hope.

**Comment by ykaragol** [comment]
Thank you!
